# Generated by Django 2.0.3 on 2018-04-19 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='adv',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_advertisement_task', models.CharField(max_length=200)),
                ('f_advertisement_text', models.CharField(max_length=1000)),
                ('f_advertisement_user', models.CharField(max_length=100)),
                ('f_advertisement_image', models.CharField(max_length=1000)),
                ('f_publication_date', models.DateTimeField(verbose_name='data published')),
            ],
        ),
        migrations.CreateModel(
            name='adv_ans',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adv_ans', models.CharField(max_length=10000)),
            ],
        ),
        migrations.CreateModel(
            name='forum_users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='choice',
            name='question',
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
